{{- if .Values.createConfigMap}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-configmap
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: {{ .Values.port }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  type: {{ .Values.serviceType }}

