name: <+pipeline.stages.Build.spec.execution.steps.get_project_info.output.outputVariables.projectName>
replicas: 1
image: <+artifact.image>
port: 8080
targetPort: 8080
serviceType: LoadBalancer

namespace:
  name: <+infra.namespace>

env:
  config:
    namespace: <+infra.namespace>